In [241]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [242]:
df=pd.read_csv('KNN.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.461538,0.681481,0.50000,0.583333,0.000000,0.495177,0.248416,0.674419,1
1,0.076923,0.214815,0.40625,0.483333,0.000000,0.270096,0.123529,0.232558,0
2,0.615385,0.940741,0.37500,0.000000,0.000000,0.163987,0.268778,0.255814,1
3,0.076923,0.244444,0.40625,0.383333,0.289231,0.318328,0.040271,0.000000,0
4,0.000000,0.600000,0.00000,0.583333,0.516923,0.800643,1.000000,0.279070,1
...,...,...,...,...,...,...,...,...,...
640,0.769231,0.333333,0.56250,0.800000,0.553846,0.472669,0.042081,0.976744,0
641,0.153846,0.488889,0.46875,0.450000,0.000000,0.598071,0.118552,0.139535,0
642,0.384615,0.448148,0.50000,0.383333,0.344615,0.257235,0.075566,0.209302,0
643,0.076923,0.518519,0.31250,0.000000,0.000000,0.382637,0.122624,0.604651,1
644,0.076923,0.274074,0.46875,0.516667,0.000000,0.392283,0.107240,0.046512,0

In [243]:
x1=df.drop('Outcome',axis=1)

In [244]:
y1=df['Outcome']

In [245]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.25,random_state=42)

In [246]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=45)

In [247]:
model=dt.fit(x1_train,y1_train)

In [248]:
y_prd=model.predict(x1_test)
y_prd

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0])

In [249]:
y1_test

632    1
592    1
599    0
291    0
72     0
      ..
591    0
326    0
318    0
271    0
140    0
Name: Outcome, Length: 162, dtype: int64

In [250]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_prd,y1_test))

0.6728395061728395

In [251]:
#sample prediction

In [252]:
x1_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
212,0.923077,0.448148,0.343750,0.116667,0.793846,0.302251,0.383710,0.534884
43,0.384615,0.237037,0.406250,0.350000,0.070769,0.199357,0.119457,0.209302
42,0.076923,0.333333,0.156250,0.250000,0.110769,0.192926,0.202715,0.116279
73,0.076923,0.177778,0.234375,0.000000,0.000000,0.028939,0.081448,0.000000
320,0.076923,0.251852,0.343750,0.300000,0.181538,0.221865,0.538462,0.093023

In [253]:
y1_train.head()

212    1
43     0
42     0
73     0
320    0
Name: Outcome, dtype: int64

In [254]:
a=list(x1_train.loc[73].values)
a

[np.float64(0.0769230769230769),
 np.float64(0.1777777777777777),
 np.float64(0.234375),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0289389067524117),
 np.float64(0.0814479638009049),
 np.float64(0.0)]

In [255]:
model.predict([[0.0769230769230769, 0.1777777777777777,0.234375,0.0,0.0, 0.0289389067524117,0.0814479638009049,0.0]])

C:\Users\firoz\OneDrive\Videos\Documents\ML 1 WEEK\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])