In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
df=pd.read_csv('KNN.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.461538,0.681481,0.50000,0.583333,0.000000,0.495177,0.248416,0.674419,1
1,0.076923,0.214815,0.40625,0.483333,0.000000,0.270096,0.123529,0.232558,0
2,0.615385,0.940741,0.37500,0.000000,0.000000,0.163987,0.268778,0.255814,1
3,0.076923,0.244444,0.40625,0.383333,0.289231,0.318328,0.040271,0.000000,0
4,0.000000,0.600000,0.00000,0.583333,0.516923,0.800643,1.000000,0.279070,1
...,...,...,...,...,...,...,...,...,...
640,0.769231,0.333333,0.56250,0.800000,0.553846,0.472669,0.042081,0.976744,0
641,0.153846,0.488889,0.46875,0.450000,0.000000,0.598071,0.118552,0.139535,0
642,0.384615,0.448148,0.50000,0.383333,0.344615,0.257235,0.075566,0.209302,0
643,0.076923,0.518519,0.31250,0.000000,0.000000,0.382637,0.122624,0.604651,1
644,0.076923,0.274074,0.46875,0.516667,0.000000,0.392283,0.107240,0.046512,0

In [93]:
x=df.drop('Outcome',axis=1)
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.461538,0.681481,0.50000,0.583333,0.000000,0.495177,0.248416,0.674419
1,0.076923,0.214815,0.40625,0.483333,0.000000,0.270096,0.123529,0.232558
2,0.615385,0.940741,0.37500,0.000000,0.000000,0.163987,0.268778,0.255814
3,0.076923,0.244444,0.40625,0.383333,0.289231,0.318328,0.040271,0.000000
4,0.000000,0.600000,0.00000,0.583333,0.516923,0.800643,1.000000,0.279070
...,...,...,...,...,...,...,...,...
640,0.769231,0.333333,0.56250,0.800000,0.553846,0.472669,0.042081,0.976744
641,0.153846,0.488889,0.46875,0.450000,0.000000,0.598071,0.118552,0.139535
642,0.384615,0.448148,0.50000,0.383333,0.344615,0.257235,0.075566,0.209302
643,0.076923,0.518519,0.31250,0.000000,0.000000,0.382637,0.122624,0.604651
644,0.076923,0.274074,0.46875,0.516667,0.000000,0.392283,0.107240,0.046512

In [94]:
y=df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
640    0
641    0
642    0
643    1
644    0
Name: Outcome, Length: 645, dtype: int64

In [95]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=25)

In [96]:
from sklearn.ensemble import RandomForestClassifier
rr=RandomForestClassifier(random_state=42,n_estimators=100,bootstrap=True,oob_score=True )

In [97]:
rr_model=rr.fit(x_train,y_train)

In [98]:
y_pred=rr_model.predict(x_test)

In [99]:
y_test

632    1
592    1
599    0
291    0
72     0
643    1
597    0
396    0
511    1
174    1
362    0
177    0
181    1
81     0
118    0
319    0
360    1
155    1
69     0
10     1
443    0
63     0
375    0
54     1
529    1
Name: Outcome, dtype: int64

In [100]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85        14
           1       1.00      0.55      0.71        11

    accuracy                           0.80        25
   macro avg       0.87      0.77      0.78        25
weighted avg       0.85      0.80      0.79        25

In [101]:
rr.oob_score_

0.7709677419354839

In [102]:
# from sklearn.metrics import accuracy_score,confusion_matrix
# print(accuracy_score(y_test,y_pred))

0.8